export enum ITicketStatus {
  DRAFT = "DRAFT",
  BACKLOG = "BACKLOG",
  NEED_INFORMATION = "NEED_INFORMATION",
  READY_FOR_DEV = "READY_FOR_DEV",
  IN_PROGRESS = "IN_PROGRESS",
  READY_FOR_TEST = "READY_FOR_TEST",
  TESTING = "TESTING",
  RELEASE_CANDIDATE = "RELEASE_CANDIDATE",
  DONE = "DONE",
  REJECTED = "REJECTED",
}
